### ISSUE TITLE
Handling ssl connexion

### ISSUE THREAD

**Issue by BotellaA** [Kitware/wslink#112]
**Is your feature request related to a problem? Please describe.**

We want to create a wss connexion using wslink and aiohttp. There is no wslink argument to activate the secure connexion.

**Describe the solution you'd like**

Allow forwarding a ssl_context to the aiohttp server.

**Describe alternatives you've considered**

We do not see an alternative without forking.

**Additional context**

We are creating a hosted https web app with wslink as a backend. This is why we need the ssl_context.

**Comment by jourdain** [comment]
We initially aim to always have apache/nginx/caddy as front-end to provide encryption.

Having ssl as a requirement could be a source of problem if not kept up-to-date. 

Are you sure, you need ssl to be managed within the Python layer?

**Comment by BotellaA** [comment]
We are using an AWS LoadBalancer in https that forwards the traffic to AWS Fargate, in which we have the wslink backend. The forwarding protocol from the load balancer cannot be changed from https to http. We understand your concerns but in this case, we do not see how to use wslink without https.

**Comment by jourdain** [comment]
Could you submit a PR with the change needed to support your use-case? Ideally, I would like to have it via an optional path such as `pip install "wslink[ssl]"` or something like that.

Let me know what you think.

**Comment by BotellaA** [comment]
We will try to implement what is needed and do a PR next month.
