### ISSUE TITLE
ImJoy-RPC backend?

### ISSUE THREAD

**Issue by banesullivan** [Kitware/wslink#130]
Would it be possible to leverage imjoy-rpc as a communication backend for `wslink` (and this `trame`)? https://github.com/imjoy-team/imjoy-rpc

Does this even make sense?

ImJoy-rpc has a lot of the Jupyter nuances figured and is quite an awesome tool. It'd be great if we could leverage all of the success it's had on Jupyter and Google Colab.

cc @thewtex

**Comment by jourdain** [comment]
Maybe but after a quick glance at imjoy-rpc, it won't be trivial task as it is not a 1-1 matching capability.

**Comment by jourdain** [comment]
We now(ish) have a jupyter backend. So closing...
