### ISSUE TITLE
RPC call application.exit.later unsuccessful: connection not open

### ISSUE THREAD

**Issue by jinjilynn** [Kitware/wslink#139]
Hey guys, I've encountered a problem. When we call the destroy method of SmartConnect, the cleanUp function within it initiates a session.close operation first. This results in an error when the destroy method of WebsocketConnection is called immediately afterwards, as model.session.call('application.exit.later', [timeout]) is called on a session that's already been closed.
Besides, could you help explain the function of 'application.exit.later' to me?

```javascript
{code: -32099, message: 'RPC call application.exit.later unsuccessful: connection not open'}
```

**Comment by jourdain** [comment]
Close later allow the server to properly exit once the network is fully disconnected and taking care.
