### ISSUE TITLE
Is it possible to support modifying the default mouse behavior?

### ISSUE THREAD

**Issue by a1401358759** [Kitware/wslink#149]
**Is your feature request related to a problem? Please describe.**

I want to implement length measurement on VR, so I want to change the left mouse button to measure length behavior and the right mouse button to rotate behavior

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

![image](https://github.com/Kitware/wslink/assets/15830146/e4a46161-f8f0-44e6-b733-7507979c0975)

**Comment by jourdain** [comment]
That would happen on the server side rather than on the network layer.
