### ISSUE TITLE
Invalid f-string

### ISSUE THREAD

**Issue by banesullivan-kobold** [Kitware/wslink#150]
https://github.com/Kitware/wslink/blob/9a6243c7029cda26a827590210783b030e49ca01/python/src/wslink/backends/aiohttp/__init__.py#L114

**Comment by banesullivan-kobold** [comment]
I see now that this was reffering to the following code block and a `print` statement is used there.

**Comment by jourdain** [comment]
Sure but the "f" could go away ;-)

**Comment by banesullivan-kobold** [comment]
Its handled in #152
