### ISSUE TITLE
aiohttp backend needs its own logger

### ISSUE THREAD

**Issue by banesullivan-kobold** [Kitware/wslink#151]
https://github.com/Kitware/wslink/blob/9a6243c7029cda26a827590210783b030e49ca01/python/src/wslink/backends/aiohttp/__init__.py#L101

This module is currently using the `root` logger. It should be using its own logger, e.g.:

```py
import logging
logger = logging.getLogger(__name__)
```

**Comment by banesullivan-kobold** [comment]
This results in noisy logs at the root level for PyVista's Jupyter backend

![Screenshot 2023-10-24 at 11 46 48 AM](https://github.com/Kitware/wslink/assets/144726278/8e24efda-1a1a-421c-abeb-08972096eb62)

**Comment by banesullivan-kobold** [comment]
This needs to be addressed for all modules under `wslink.backends.aiohttp`

**Comment by jourdain** [comment]
indeed. Feel free to do a PR.
