### ISSUE TITLE
GET and DELETE requests not working in Python 3?

### ISSUE THREAD

**Issue by finetjul** [Kitware/wslink#16]
When doing a GET or DELETE request, the launcher complains with the following error:
```
builtins.TypeError: a bytes-like object is required, not 'str'
```

Could it be that WSLink is not Python3 compliant ? 
This is my naive understanding of: https://stackoverflow.com/questions/33003498/typeerror-a-bytes-like-object-is-required-not-str

(disclaimer: I have not tried with Python2)

**Comment by aronhelser** [comment]
wslink has definitely been tested with python3. Can you say more about what configuration you are using? Does this happen with the demo/tests?

**Comment by jourdain** [comment]
I guess the GET/DELETE endpoint may not have been tested. Why do you need them @finetjul ?

**Comment by finetjul** [comment]
This error has been found while testing the launcher API by doing simple HTTP requests. I didn't try yet to use js/ProcessLauncher.

The following seems to fix the error in our case:
```
def extractSessionId(request):
    path = request.path.split(b'/')
    if len(path) < 3:
        return None
    return str(path[2], 'utf-8')
```

**Comment by aronhelser** [comment]
Got a confirmation from @martinken  that the DELETE method actually causes a crash in the python code, trying to access a missing variable.
