### ISSUE TITLE
ServerProtocol @exportRpc("application.exit") not accessible

### ISSUE THREAD

**Issue by aronhelser** [Kitware/wslink#21]
in websocket.py, the two RPC methods @exportRpc("application.exit") and @exportRpc("application.exit.later") are defined, but are not callable from the client. 

Examining WslinkWebSocketServerProtocol::onConnect, looks like only LinkProtocol objects have their RPC's registered, and not the ServerProtocol.

Reported by @martinken

**Comment by aronhelser** [comment]
The workaround is to depend on the server timeout, and shorten the timeout if needed.

**Comment by jourdain** [comment]
This seems to be fixed now
