### ISSUE TITLE
Path segment must be bytes error in link 699 of wslink/launcher.py

### ISSUE THREAD

**Issue by rasunag27** [Kitware/wslink#66]
Hello,

I am running a Paraview lite visualizer as a multi-user with apache2. For this, I have given the paraview path to Paraview - 5.9.1. 

1. I need to run "start.sh" file from terminal which contains wslink/launcher.py.

2. When I run "start.sh" file, I am addressing the following error:

```
/data/pv/pv-5.9.1/lib/python3.8/site-packages/wslink/launcher.py:699: DeprecationWarning: Path segment must be bytes; passing <class 'str'> has never worked, and will raise an exception in the future.
  web_resource.putChild("upload", uploadResource)
```
3. I tried working with Paraview 5.7.0, when I run start.sh with this, It does not show any error. But, in the server "http://localhost/paraview", it should the error as addessed in the link here: [Paraview_error](https://drive.google.com/file/d/1hNhlvkHyUN95QUrdAiSGt84i7rRzIdg7/view?usp=sharing)

4. Any leads will be appreciated. Do the needful.

Regards,

Sunag R A.

**Comment by jourdain** [comment]
Just remove the `upload` key in your config.
